export interface MoleculeRecord {
  id: number;
  molecule: string;
  submittedCountries: number;
  notSubmittedCountries: number;
  products: number;
  variantsSku: number;
  submissions: number;
  rejections: number;
  overdueActivity: number;
  blackout: string;
  healthy: number;
}

export const INITIAL_MOLECULE_RECORDS: MoleculeRecord[] = [
  {
    id: 1,
    molecule: 'Enoxaparin Sodium',
    submittedCountries: 40,
    notSubmittedCountries: 12,
    products: 3,
    variantsSku: 9,
    submissions: 52,
    rejections: 3,
    overdueActivity: 4,
    blackout: '2/40',
    healthy: 86,
  },
  {
    id: 2,
    molecule: 'Atorvastatin',
    submittedCountries: 34,
    notSubmittedCountries: 18,
    products: 3,
    variantsSku: 12,
    submissions: 61,
    rejections: 5,
    overdueActivity: 2,
    blackout: '1/34',
    healthy: 91,
  },
  {
    id: 3,
    molecule: 'Ceftriaxone',
    submittedCountries: 22,
    notSubmittedCountries: 30,
    products: 2,
    variantsSku: 6,
    submissions: 29,
    rejections: 4,
    overdueActivity: 6,
    blackout: '3/22',
    healthy: 72,
  },
  {
    id: 4,
    molecule: 'Iohexol',
    submittedCountries: 18,
    notSubmittedCountries: 34,
    products: 2,
    variantsSku: 4,
    submissions: 24,
    rejections: 1,
    overdueActivity: 1,
    blackout: '0/18',
    healthy: 94,
  },
  {
    id: 5,
    molecule: 'Ondansetron',
    submittedCountries: 27,
    notSubmittedCountries: 25,
    products: 2,
    variantsSku: 5,
    submissions: 33,
    rejections: 2,
    overdueActivity: 3,
    blackout: '1/27',
    healthy: 83,
  },
  {
    id: 6,
    molecule: 'Metformin HCl',
    submittedCountries: 44,
    notSubmittedCountries: 8,
    products: 2,
    variantsSku: 7,
    submissions: 58,
    rejections: 2,
    overdueActivity: 0,
    blackout: '0/44',
    healthy: 96,
  },
  {
    id: 7,
    molecule: 'Amlodipine Besylate',
    submittedCountries: 38,
    notSubmittedCountries: 14,
    products: 3,
    variantsSku: 8,
    submissions: 48,
    rejections: 1,
    overdueActivity: 2,
    blackout: '1/38',
    healthy: 92,
  },
  {
    id: 8,
    molecule: 'Pantoprazole',
    submittedCountries: 31,
    notSubmittedCountries: 21,
    products: 2,
    variantsSku: 6,
    submissions: 39,
    rejections: 3,
    overdueActivity: 1,
    blackout: '2/31',
    healthy: 88,
  },
  {
    id: 9,
    molecule: 'Rosuvastatin',
    submittedCountries: 29,
    notSubmittedCountries: 23,
    products: 3,
    variantsSku: 10,
    submissions: 45,
    rejections: 2,
    overdueActivity: 4,
    blackout: '1/29',
    healthy: 85,
  },
  {
    id: 10,
    molecule: 'Levofloxacin',
    submittedCountries: 25,
    notSubmittedCountries: 27,
    products: 2,
    variantsSku: 5,
    submissions: 31,
    rejections: 4,
    overdueActivity: 5,
    blackout: '2/25',
    healthy: 79,
  },
  {
    id: 11,
    molecule: 'Azithromycin',
    submittedCountries: 42,
    notSubmittedCountries: 10,
    products: 4,
    variantsSku: 11,
    submissions: 56,
    rejections: 1,
    overdueActivity: 1,
    blackout: '0/42',
    healthy: 95,
  },
  {
    id: 12,
    molecule: 'Paracetamol',
    submittedCountries: 48,
    notSubmittedCountries: 4,
    products: 3,
    variantsSku: 8,
    submissions: 64,
    rejections: 0,
    overdueActivity: 0,
    blackout: '0/48',
    healthy: 99,
  },
  {
    id: 13,
    molecule: 'Ibuprofen',
    submittedCountries: 36,
    notSubmittedCountries: 16,
    products: 2,
    variantsSku: 7,
    submissions: 42,
    rejections: 2,
    overdueActivity: 2,
    blackout: '1/36',
    healthy: 90,
  },
  {
    id: 14,
    molecule: 'Omeprazole',
    submittedCountries: 33,
    notSubmittedCountries: 19,
    products: 3,
    variantsSku: 9,
    submissions: 44,
    rejections: 3,
    overdueActivity: 3,
    blackout: '2/33',
    healthy: 84,
  },
  {
    id: 15,
    molecule: 'Clopidogrel',
    submittedCountries: 35,
    notSubmittedCountries: 17,
    products: 2,
    variantsSku: 6,
    submissions: 40,
    rejections: 1,
    overdueActivity: 1,
    blackout: '1/35',
    healthy: 93,
  },
];
